# Generated by Django 5.0.9 on 2024-09-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_roll_app', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
