# Generated by Django 5.0.9 on 2024-09-29 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_roll_app', '0004_country_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='department_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='pay_roll_app.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='pay_roll_app.department'),
        ),
    ]
